---
controller_roles:
  - user: "test_user@xyz.com"
    job_template: "aap_controller_configuration_template-dev"
    roles:
      - read
      - execute
      - admin
    wait: true
  - inventory: "aap-sandbox"
    user: admin
    roles: 
      - read
    wait: true
  
  - team:
      - "Infrastructure Team"
    project: "Demo Project 1" 
    roles:
      - execute
      - read
    state: present
    wait: true